os: linux
language: scala
dist: bionic
addons:
  apt:
    update: true

jdk:
  - openjdk8

script:
  - export PATH=~/bin/mill:$PATH
  - ./mill -i __.test

cache:
  directories:
    - $HOME/.cache/coursier/v1
    - $HOME/.mill
